version: '3'
services:
  db:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=cinema
      - POSTGRES_USER=cinemauser
      - POSTGRES_PASSWORD=cinemapassword
      - PGDATA=var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  postgres-it:
    image: postgres:15-alpine
    ports:
      - "5332:5432"
    environment:
      - POSTGRES_DB=cinema
      - POSTGRES_USER=cinemauser
      - POSTGRES_PASSWORD=cinemapassword
      - PGDATA=var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - db


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: