server:
    port: 0

spring:
    application:
        name: cinema-poc
    datasource:
        url: jdbc:postgresql://localhost:5332/cinema
        username: cinemauser
        password: cinemapassword
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true